= How to write SLF4J logs into file; i.e. How to customize Logback configuration in Katalon Studio

This is a link:https://katalon.com/katalon-studio[Katalon Studio] for demonstration purpose.
You can download the zip from the link:https://github.com/kazurayam/HowToWriteSLF4JLogsIntoFile/releases/[Releases] page on the GitHub.

This project was created using link:https://github.com/katalon-studio/katalon-studio/releases[version 8.3.0] but it should work on any versions.

I created this project in the hope that it can reply to an old question posted in the Katalon user forum at April 2019:

- link:https://forum.katalon.com/t/write-the-sl4j-logs-into-a-text-file/23332["Write the slf4j logs into a text file"]

== Problem to solve

In a Katalon Studio project, I created link:https://github.com/kazurayam/HowToWriteSLF4JLogsIntoFile/blob/develop/Scripts/runMyApp3/Script1683151952333.groovy[`Test Cases/runMyApps`]:

[source]
----
include::Scripts/runMyApp3/Script1683151952333.groovy[]
----

`runMyApps` calls a Groovy class.

- link:https://github.com/kazurayam/HowToWriteSLF4JLogsIntoFile/blob/develop/Keywords/com/kazurayam/myapp/MyApp3.groovy[`Keywords/com/kazurayam/myapp/MyApp3.groovy`]:

This calls another Groovy class:

- link:https://github.com/kazurayam/HowToWriteSLF4JLogsIntoFile/blob/develop/Keywords/com/kazurayam/myapp/Foo.groovy[]

[source]
----
include::Keywords/com/kazurayam/myapp/Foo.groovy[]
----

If you read the source of the `Foo` class, you would notice that it generates quite a lot of logs (1000 lines) using the `org.slf4j.Logger`. And each line of log will be very long (3.8K characters actually). The size of log will be 1000 * 3.8K = 3.8Mega characters.

I rand the `Test Cases/runMyApp`. I got the following result:


